version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5000:5000"

  # 1. Your Custom C# MCP Server
  mcp-csharp:
    build:
      context: .
      dockerfile: McpServer/Dockerfile
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - DOTNET_ENVIRONMENT=Production

  # 2. n8n (The Client)
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_client
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=localhost
      - N8N_SKIP_RESPONSE_COMPRESSION=true
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: